language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"

cache:
  directories:
    - $HOME/.cache/pip

install:
    - make requirements
    - pip install coveralls

script:
    - make test

after_success:
    - coveralls

services:
    - redis
