site_name: simple-settings
site_description: A simple way to manage your project settings.
site_author: Diego Garcia

repo_url: https://github.com/drgarcia1986/simple-settings/
site_url: http://simple-settings.readthedocs.org/en/latest/
theme: readthedocs

pages:
    - ['index.md', 'Home']
